abstract final class AppRoutes {
  static const init = '/';
  static const welcome = '/welcome';
  static const login = '/login';
  static const role = '/role';
  static const register = '/register';
  static const forgotPassword = '/forgot-password';
  static const updatePassword = '/update-password';
  static const home = '/home';
  static const report = '/report';
  static const reportManager = '/report/managers/:id';
  static const reportTable = '/report/tables/:id';
  static const profile = '/profile';
  static const settings = '/settings';
  static const tableForm = '/tables/form';
  static const tableDetail = '/tables/detail';
  static const venueForm = '/venues/form';
  static const venuesList = '/venues';
  static const venueDetail = '/venues/detail';
  static const managers = '/managers';
  static const subscription = '/subscription';
  static const subscriptionCheckout = '/subscription/checkout';
  static const subscriptionPayment = '/subscription/payment';
}
