abstract final class AppRoutes {
  static const init = '/';
  static const welcome = '/welcome';
  static const login = '/login';
  static const role = '/role';
  static const register = '/register';
  static const forgotPassword = '/forgot-password';
  static const updatePassword = '/update-password';
  static const home = '/home';
  static const report = '/report';
  static const reportManager = '/report/managers/:id/:venueId';
  static const reportSpot = '/report/spots/:id/:venueId';
  static const profile = '/profile';
  static const settings = '/settings';
  static const spotForm = '/spots/form';
  static const spotDetail = '/spots/detail';
  static const venueForm = '/venues/form';
  static const venuesList = '/venues';
  static const venueDetail = '/venues/detail';
  static const managers = '/managers';
  static const subscription = '/subscription';
  static const subscriptionCheckout = '/subscription/checkout';
  static const subscriptionPayment = '/subscription/payment';
  static const products = '/products';
  static const productForm = '/products/form';
}
