name: sport_manager_mobile
resolution: workspace
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+9

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  meta:
  intl:
  equatable:
  flutter_bloc:
  go_router:
  core:
  api_client:
  firebase_core:
  firebase_remote_config:
  storage_client:
  auth:
  facility:
  managers:
  subscription:
  reports:
  cupertino_icons:
  get_it:
  toastification:
  google_fonts:
  mask_text_input_formatter:
  flutter_svg:
  syncfusion_flutter_charts:
  package_info_plus:
  url_launcher:
  talker_flutter:
  talker_dio_logger:

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail:
  flutter_gen_runner:
  flutter_launcher_icons:
  flutter_native_splash:

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/

flutter_gen:
  output: lib/generated/
  line_length: 120
  integrations:
    flutter_svg: true
    rive: false
    lottie: false
