import 'package:flutter/material.dart';
import 'package:sport_manager_mobile/ui/ui.dart';

abstract final class AppColorSchemes {
  static const ColorScheme light = ColorScheme(
    brightness: Brightness.light,
    primary: AppColors.brandAmber,
    onPrimary: AppColors.white,
    primaryContainer: AppColors.brandAmberLight,
    onPrimaryContainer: AppColors.brandAmberDark,
    secondary: AppColors.successGreen,
    onSecondary: AppColors.white,
    secondaryContainer: AppColors.successLight,
    onSecondaryContainer: AppColors.successDark,
    tertiary: AppColors.infoCyan,
    onTertiary: AppColors.white,
    tertiaryContainer: AppColors.infoLight,
    onTertiaryContainer: AppColors.infoCyan,
    error: AppColors.dangerRed,
    onError: AppColors.white,
    errorContainer: AppColors.dangerLight,
    onErrorContainer: AppColors.dangerDark,
    surface: AppColors.white,
    onSurface: AppColors.ink900,
    onSurfaceVariant: AppColors.ink500,
    surfaceContainerLowest: AppColors.white,
    surfaceContainerLow: AppColors.bgWarm,
    surfaceContainer: AppColors.white,
    surfaceContainerHigh: AppColors.ink100,
    surfaceContainerHighest: AppColors.ink100,
    outline: AppColors.ink300,
    outlineVariant: AppColors.ink100,
    shadow: AppColors.black,
    scrim: AppColors.black,
    inverseSurface: AppColors.ink900,
    onInverseSurface: AppColors.white,
    inversePrimary: AppColors.brandAmberLight,
    surfaceTint: AppColors.brandAmber,
  );

  static const ColorScheme dark = ColorScheme(
    brightness: Brightness.dark,
    primary: AppColors.brandAmber,
    onPrimary: AppColors.white,
    primaryContainer: AppColors.brandAmberDark,
    onPrimaryContainer: AppColors.brandAmberLight,
    secondary: AppColors.successGreen,
    onSecondary: AppColors.white,
    secondaryContainer: AppColors.successDark,
    onSecondaryContainer: AppColors.successLight,
    tertiary: AppColors.infoCyan,
    onTertiary: AppColors.white,
    tertiaryContainer: AppColors.infoDark,
    onTertiaryContainer: AppColors.infoLight,
    error: AppColors.dangerRed,
    onError: AppColors.white,
    errorContainer: AppColors.dangerDark,
    onErrorContainer: AppColors.dangerLight,
    surface: AppColors.darkBgSecondary,
    onSurface: AppColors.white,
    onSurfaceVariant: AppColors.ink300,
    surfaceContainerLowest: AppColors.darkBgPrimary,
    surfaceContainerLow: AppColors.darkBgPrimary,
    surfaceContainer: AppColors.darkBgSecondary,
    surfaceContainerHigh: AppColors.darkBgSecondary,
    surfaceContainerHighest: AppColors.darkBgTertiary,
    outline: AppColors.darkBgBorder,
    outlineVariant: AppColors.ink700,
    shadow: AppColors.black,
    scrim: AppColors.black,
    inverseSurface: AppColors.ink100,
    onInverseSurface: AppColors.ink900,
    inversePrimary: AppColors.brandAmberDark,
    surfaceTint: AppColors.brandAmber,
  );
}
