import 'package:flutter/material.dart';
import 'package:sport_manager_mobile/ui/theme/colors/brand_colors.dart';
import 'package:sport_manager_mobile/ui/theme/colors/neutral_colors.dart';
import 'package:sport_manager_mobile/ui/theme/colors/semantic_colors.dart';
import 'package:sport_manager_mobile/ui/theme/colors/surface_colors.dart';

abstract final class AppColorSchemes {
  static const ColorScheme light = ColorScheme(
    brightness: Brightness.light,
    primary: BrandColors.amber,
    onPrimary: NeutralColors.white,
    primaryContainer: BrandColors.amberLight,
    onPrimaryContainer: BrandColors.amberDark,
    secondary: SemanticColors.successGreen,
    onSecondary: NeutralColors.white,
    secondaryContainer: SemanticColors.successLight,
    onSecondaryContainer: SemanticColors.successDark,
    tertiary: SemanticColors.infoCyan,
    onTertiary: NeutralColors.white,
    tertiaryContainer: SemanticColors.infoLight,
    onTertiaryContainer: SemanticColors.infoCyan,
    error: SemanticColors.dangerRed,
    onError: NeutralColors.white,
    errorContainer: SemanticColors.dangerLight,
    onErrorContainer: SemanticColors.dangerDark,
    surface: NeutralColors.white,
    onSurface: NeutralColors.ink900,
    onSurfaceVariant: NeutralColors.ink500,
    surfaceContainerLowest: NeutralColors.white,
    surfaceContainerLow: SurfaceColors.bgWarm,
    surfaceContainer: NeutralColors.white,
    surfaceContainerHigh: NeutralColors.ink100,
    surfaceContainerHighest: NeutralColors.ink100,
    outline: NeutralColors.ink300,
    outlineVariant: NeutralColors.ink100,
    shadow: NeutralColors.black,
    scrim: NeutralColors.black,
    inverseSurface: NeutralColors.ink900,
    onInverseSurface: NeutralColors.white,
    inversePrimary: BrandColors.amberLight,
    surfaceTint: BrandColors.amber,
  );

  static const ColorScheme dark = ColorScheme(
    brightness: Brightness.dark,
    primary: BrandColors.amber,
    onPrimary: NeutralColors.white,
    primaryContainer: BrandColors.amberDark,
    onPrimaryContainer: BrandColors.amberLight,
    secondary: SemanticColors.successGreen,
    onSecondary: NeutralColors.white,
    secondaryContainer: SemanticColors.successDark,
    onSecondaryContainer: SemanticColors.successLight,
    tertiary: SemanticColors.infoCyan,
    onTertiary: NeutralColors.white,
    tertiaryContainer: SemanticColors.infoCyan,
    onTertiaryContainer: NeutralColors.white,
    error: SemanticColors.dangerRed,
    onError: NeutralColors.white,
    errorContainer: SemanticColors.dangerDark,
    onErrorContainer: SemanticColors.dangerLight,
    surface: SurfaceColors.darkBgSecondary,
    onSurface: NeutralColors.white,
    onSurfaceVariant: NeutralColors.ink300,
    surfaceContainerLowest: SurfaceColors.darkBgPrimary,
    surfaceContainerLow: SurfaceColors.darkBgPrimary,
    surfaceContainer: SurfaceColors.darkBgSecondary,
    surfaceContainerHigh: SurfaceColors.darkBgSecondary,
    surfaceContainerHighest: SurfaceColors.darkBgTertiary,
    outline: SurfaceColors.darkBgBorder,
    outlineVariant: NeutralColors.ink700,
    shadow: NeutralColors.black,
    scrim: NeutralColors.black,
    inverseSurface: NeutralColors.ink100,
    onInverseSurface: NeutralColors.ink900,
    inversePrimary: BrandColors.amberDark,
    surfaceTint: BrandColors.amber,
  );
}
